/* Copyright (c) 2018 Griefer@Work                                            *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement in the product documentation would be  *
 *    appreciated but is not required.                                        *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_LIBS_LIBC_UNISTD_H
#define GUARD_LIBS_LIBC_UNISTD_H 1

#include "libc.h"
#include <kos/types.h>

#ifdef __CC__
DECL_BEGIN

/* ===================================================================================== */
/*     UNISTD                                                                            */
/* ===================================================================================== */
struct iovec;
struct file_handle;
#ifndef __nfds_t_defined
#define __nfds_t_defined 1
typedef __UINTPTR_TYPE__ nfds_t;
#endif /* !__nfds_t_defined */
INTDEF int ATTR_CDECL libc_open(char const *filename, oflag_t flags, ...);
INTDEF int ATTR_CDECL libc_openat(fd_t dfd, char const *filename, oflag_t flags, ...);
INTDEF int ATTR_CDECL libc_dos_open(char const *filename, oflag_t flags, ...);
INTDEF int ATTR_CDECL libc_dos_openat(fd_t dfd, char const *filename, oflag_t flags, ...);
INTDEF int LIBCCALL libc_creat(char const *file, mode_t mode);
INTDEF int LIBCCALL libc_dos_creat(char const *file, mode_t mode);
INTDEF ssize_t ATTR_CDECL libc_fcntl(fd_t fd, unsigned int cmd, ...);
INTDEF ssize_t ATTR_CDECL libc_ioctl(fd_t fd, unsigned long cmd, ...);
INTDEF ssize_t ATTR_CDECL libc_xioctlf(fd_t fd, unsigned long cmd, oflag_t flags, ...);
INTDEF int LIBCCALL libc_posix_fadvise(fd_t fd, pos32_t offset, pos32_t len, int advise);
INTDEF int LIBCCALL libc_posix_fadvise64(fd_t fd, pos64_t offset, pos64_t len, int advise);
INTDEF int LIBCCALL libc_posix_fallocate(fd_t fd, pos32_t offset, pos32_t len);
INTDEF int LIBCCALL libc_posix_fallocate64(fd_t fd, pos64_t offset, pos64_t len);
INTDEF int LIBCCALL libc_lockf(fd_t fd, int cmd, pos32_t len);
INTDEF int LIBCCALL libc_lockf64(fd_t fd, int cmd, pos64_t len);
INTDEF ssize_t LIBCCALL libc_readahead(fd_t fd, pos64_t offset, size_t count);
INTDEF int LIBCCALL libc_sync_file_range(fd_t fd, pos64_t offset, pos64_t count, unsigned int flags);
INTDEF ssize_t LIBCCALL libc_vmsplice(int fdout, struct iovec const *iov, size_t count, unsigned int flags);
INTDEF ssize_t LIBCCALL libc_splice(int fdin, pos64_t *offin, int fdout, pos64_t *offout, size_t len, unsigned int flags);
INTDEF ssize_t LIBCCALL libc_tee(int fdin, int fdout, size_t len, unsigned int flags);
INTDEF int LIBCCALL libc_name_to_handle_at(fd_t dfd, char const *name, struct file_handle *handle, int *mnt_id, int flags);
INTDEF int LIBCCALL libc_open_by_handle_at(int mountdirfd, struct file_handle *handle, int flags);
INTDEF int LIBCCALL libc_fallocate(fd_t fd, int mode, pos32_t offset, pos32_t len);
INTDEF int LIBCCALL libc_fallocate64(fd_t fd, int mode, pos64_t offset, pos64_t len);
INTDEF pid_t LIBCCALL libc_gettid(void);
INTDEF pid_t LIBCCALL libc_getpid(void);
INTDEF int LIBCCALL libc_pipe(int pipedes[2]);
INTDEF int LIBCCALL libc_pipe2(int pipedes[2], int flags);
INTDEF int LIBCCALL libd_pipe(int pipedes[2], u32 pipesize, int textmode);
INTDEF mode_t LIBCCALL libc_umask(mode_t new_mode);
INTDEF mode_t LIBCCALL libc_getumask(void);
INTDEF errno_t LIBCCALL libc_umask_s(mode_t new_mode, mode_t *old_mode);
INTDEF derrno_t LIBCCALL libd_umask_s(mode_t new_mode, mode_t *old_mode);
INTDEF mode_t LIBCCALL libd_setmode(fd_t fd, mode_t mode);
INTDEF int LIBCCALL _libd_lock_fhandle(fd_t fd);
INTDEF void LIBCCALL libd_unlock_fhandle(fd_t fd);
INTDEF int LIBCCALL libc_fsync(fd_t fd);
INTDEF int LIBCCALL libc_fdatasync(fd_t fd);
INTDEF uid_t LIBCCALL libc_getuid(void);
INTDEF uid_t LIBCCALL libc_geteuid(void);
INTDEF gid_t LIBCCALL libc_getgid(void);
INTDEF gid_t LIBCCALL libc_getegid(void);
INTDEF int LIBCCALL libc_getgroups(int size, gid_t list[]);
INTDEF int LIBCCALL libc_setuid(uid_t uid);
INTDEF int LIBCCALL libc_setgid(gid_t gid);
/* HANDLES */
INTDEF int LIBCCALL libc_dup(fd_t fd);
INTDEF int LIBCCALL libc_dup2(int ofd, int nfd);
INTDEF int LIBCCALL libc_dup3(int ofd, int nfd, int flags);
INTDEF int LIBCCALL libc_close(fd_t fd);
/* FILESYSTEM CONTROL */
INTDEF struct fsmask LIBCCALL libc_fsmode(struct fsmask new_mode);
INTDEF struct fsmask LIBCCALL libc_getfsmode(void);
#define LIBC_DOSMODE_ENABLED()    (libc_getfsmode().fm_mode & AT_DOSPATH)
#define LIBC_DOSMODE_DISABLED() (!(libc_getfsmode().fm_mask & AT_DOSPATH))
INTDEF int LIBCCALL libc_chdir(char const *path);
INTDEF int LIBCCALL libc_dos_chdir(char const *path);
INTDEF int LIBCCALL libc_fchdirat(fd_t dfd, char const *path, int flags);
INTDEF int LIBCCALL libc_dos_fchdirat(fd_t dfd, char const *path, int flags);
INTDEF int LIBCCALL libc_fchdir(fd_t fd);
INTDEF char *LIBCCALL libc_getcwd(char *buf, size_t size);
INTDEF char *LIBCCALL libc_dos_getcwd(char *buf, size_t size);
INTDEF char *LIBCCALL libc_getwd(char *buf);
INTDEF char *LIBCCALL libc_dos_getwd(char *buf);
INTDEF char *LIBCCALL libc_get_current_dir_name(void);
INTDEF char *LIBCCALL libc_dos_get_current_dir_name(void);
INTDEF char *LIBCCALL libc_xfdname(fd_t fd, int type, char *buf, size_t bufsize);
INTDEF char *LIBCCALL libc_dos_xfdname(fd_t fd, int type, char *buf, size_t bufsize);
INTDEF char *LIBCCALL libc_xfrealpath(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF char *LIBCCALL libc_dos_xfrealpath(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF char *LIBCCALL libc_xrealpath(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF char *LIBCCALL libc_dos_xrealpath(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF char *LIBCCALL libc_xfrealpathat(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF char *LIBCCALL libc_dos_xfrealpathat(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_xfdname2(fd_t fd, int type, char *buf, size_t bufsize);
INTDEF ssize_t LIBCCALL libc_dos_xfdname2(fd_t fd, int type, char *buf, size_t bufsize);
INTDEF ssize_t LIBCCALL libc_xfrealpath2(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_dos_xfrealpath2(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_xrealpath2(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_dos_xrealpath2(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_xfrealpathat2(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF ssize_t LIBCCALL libc_dos_xfrealpathat2(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF long int LIBCCALL libc_pathconf(char const *path, int name);
INTDEF long int LIBCCALL libc_dos_pathconf(char const *path, int name);
INTDEF long int LIBCCALL libc_fpathconfat(fd_t dfd, char const *file, int name, int flags);
INTDEF long int LIBCCALL libc_dos_fpathconfat(fd_t dfd, char const *file, int name, int flags);
INTDEF long int LIBCCALL libc_fpathconf(fd_t fd, int name);
INTDEF char *LIBCCALL libc_realpath(char const *name, char *resolved);
INTDEF char *LIBCCALL libc_dos_realpath(char const *name, char *resolved);
INTDEF char *LIBCCALL libc_frealpath(fd_t fd, char *resolved, size_t bufsize);
INTDEF char *LIBCCALL libc_dos_frealpath(fd_t fd, char *resolved, size_t bufsize);
INTDEF ATTR_MALLOC char *LIBCCALL libc_canonicalize_file_name(char const *name);
INTDEF ATTR_MALLOC char *LIBCCALL libc_dos_canonicalize_file_name(char const *name);
/* FILESYSTEM OPERATIONS */
INTDEF int LIBCCALL libc_chown(char const *file, uid_t owner, gid_t group);
INTDEF int LIBCCALL libc_dos_chown(char const *file, uid_t owner, gid_t group);
INTDEF int LIBCCALL libc_fchown(fd_t fd, uid_t owner, gid_t group);
INTDEF int LIBCCALL libc_lchown(char const *file, uid_t owner, gid_t group);
INTDEF int LIBCCALL libc_dos_lchown(char const *file, uid_t owner, gid_t group);
INTDEF int LIBCCALL libc_fchownat(fd_t dfd, char const *file, uid_t owner, gid_t group, int flags);
INTDEF int LIBCCALL libc_dos_fchownat(fd_t dfd, char const *file, uid_t owner, gid_t group, int flags);
INTDEF int LIBCCALL libc_fchmod(fd_t fd, mode_t mode);
INTDEF int LIBCCALL libc_chmod(char const *file, mode_t mode);
INTDEF int LIBCCALL libc_dos_chmod(char const *file, mode_t mode);
INTDEF int LIBCCALL libc_lchmod(char const *file, mode_t mode);
INTDEF int LIBCCALL libc_dos_lchmod(char const *file, mode_t mode);
INTDEF int LIBCCALL libc_fchmodat(fd_t dfd, char const *file, mode_t mode, int flags);
INTDEF int LIBCCALL libc_dos_fchmodat(fd_t dfd, char const *file, mode_t mode, int flags);
INTDEF int LIBCCALL libc_link(char const *from, char const *to);
INTDEF int LIBCCALL libc_dos_link(char const *from, char const *to);
INTDEF int LIBCCALL libc_linkat(int fromfd, char const *from, int tofd, char const *to, int flags);
INTDEF int LIBCCALL libc_dos_linkat(int fromfd, char const *from, int tofd, char const *to, int flags);
INTDEF int LIBCCALL libc_unlink(char const *name);
INTDEF int LIBCCALL libc_dos_unlink(char const *name);
INTDEF int LIBCCALL libc_unlinkat(fd_t dfd, char const *name, int flags);
INTDEF int LIBCCALL libc_dos_unlinkat(fd_t dfd, char const *name, int flags);
INTDEF int LIBCCALL libc_rmdir(char const *name);
INTDEF int LIBCCALL libc_dos_rmdir(char const *name);
INTDEF int LIBCCALL libc_remove(char const *name);
INTDEF int LIBCCALL libc_dos_remove(char const *name);
INTDEF int LIBCCALL libc_removeat(fd_t dfd, char const *name);
INTDEF int LIBCCALL libc_dos_removeat(fd_t dfd, char const *name);
INTDEF int LIBCCALL libc_rename(char const *oldname, char const *newname);
INTDEF int LIBCCALL libc_dos_rename(char const *oldname, char const *newname);
INTDEF int LIBCCALL libc_renameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname);
INTDEF int LIBCCALL libc_dos_renameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname);
INTDEF int LIBCCALL libc_frenameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname, int flags);
INTDEF int LIBCCALL libc_dos_frenameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname, int flags);
INTDEF int LIBCCALL libc_mkdir1(char const *name);
INTDEF int LIBCCALL libc_dos_mkdir1(char const *name);
INTDEF int LIBCCALL libc_mkdir(char const *name, mode_t mode);
INTDEF int LIBCCALL libc_dos_mkdir(char const *name, mode_t mode);
INTDEF int LIBCCALL libc_mkdirat(fd_t dfd, char const *name, mode_t mode);
INTDEF int LIBCCALL libc_dos_mkdirat(fd_t dfd, char const *name, mode_t mode);
INTDEF int LIBCCALL libc_fmkdirat(fd_t dfd, char const *name, mode_t mode, int flags);
INTDEF int LIBCCALL libc_dos_fmkdirat(fd_t dfd, char const *name, mode_t mode, int flags);
INTDEF int LIBCCALL libc_symlink(char const *from, char const *to);
INTDEF int LIBCCALL libc_dos_symlink(char const *from, char const *to);
INTDEF int LIBCCALL libc_symlinkat(char const *from, int tofd, char const *to);
INTDEF int LIBCCALL libc_dos_symlinkat(char const *from, int tofd, char const *to);
INTDEF int LIBCCALL libc_fsymlinkat(char const *from, int tofd, char const *to, int flags);
INTDEF int LIBCCALL libc_dos_fsymlinkat(char const *from, int tofd, char const *to, int flags);
INTDEF int LIBCCALL libc_mknod(char const *path, mode_t mode, dev_t dev);
INTDEF int LIBCCALL libc_dos_mknod(char const *path, mode_t mode, dev_t dev);
INTDEF int LIBCCALL libc_mknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev);
INTDEF int LIBCCALL libc_dos_mknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev);
INTDEF int LIBCCALL libc_fmknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev, int flags);
INTDEF int LIBCCALL libc_dos_fmknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev, int flags);
INTDEF int LIBCCALL libc_xmknod(int ver, char const *path, mode_t mode, dev_t *pdev);
INTDEF int LIBCCALL libc_dos_xmknod(int ver, char const *path, mode_t mode, dev_t *pdev);
INTDEF int LIBCCALL libc_xmknodat(int ver, fd_t dfd, char const *path, mode_t mode, dev_t *pdev);
INTDEF int LIBCCALL libc_dos_xmknodat(int ver, fd_t dfd, char const *path, mode_t mode, dev_t *pdev);
INTDEF int LIBCCALL libc_mkfifo(char const *path, mode_t mode);
INTDEF int LIBCCALL libc_dos_mkfifo(char const *path, mode_t mode);
INTDEF int LIBCCALL libc_mkfifoat(fd_t dfd, char const *path, mode_t mode);
INTDEF int LIBCCALL libc_dos_mkfifoat(fd_t dfd, char const *path, mode_t mode);
INTDEF errno_t LIBCCALL libd_access_s(char const *file, int type);
INTDEF derrno_t LIBCCALL libd_dos_access_s(char const *file, int type);
INTDEF ssize_t LIBCCALL libc_freadlink(fd_t fd, char *buf, size_t buflen);
INTDEF ssize_t LIBCCALL libc_readlink(char const *path, char *buf, size_t buflen);
INTDEF ssize_t LIBCCALL libc_dos_readlink(char const *path, char *buf, size_t buflen);
INTDEF ssize_t LIBCCALL libc_readlinkat(fd_t dfd, char const *path, char *buf, size_t buflen);
INTDEF ssize_t LIBCCALL libc_dos_readlinkat(fd_t dfd, char const *path, char *buf, size_t buflen);
INTDEF ssize_t LIBCCALL libc_freadlinkat(fd_t dfd, char const *path, char *buf, size_t buflen, int flags);
INTDEF ssize_t LIBCCALL libc_dos_freadlinkat(fd_t dfd, char const *path, char *buf, size_t buflen, int flags);
INTDEF int LIBCCALL libc_access(char const *name, int type);
INTDEF int LIBCCALL libc_dos_access(char const *name, int type);
INTDEF int LIBCCALL libc_eaccess(char const *name, int type);
INTDEF int LIBCCALL libc_dos_eaccess(char const *name, int type);
INTDEF int LIBCCALL libc_faccessat(fd_t dfd, char const *file, int type, int flags);
INTDEF int LIBCCALL libc_dos_faccessat(fd_t dfd, char const *file, int type, int flags);
INTDEF int LIBCCALL libc_ftruncate(fd_t fd, pos32_t length);
INTDEF int LIBCCALL libc_ftruncate64(fd_t fd, pos64_t length);
INTDEF int LIBCCALL libc_truncate(char const *file, pos32_t length);
INTDEF int LIBCCALL libc_truncate64(char const *file, pos64_t length);
INTDEF int LIBCCALL libc_dos_truncate(char const *file, pos32_t length);
INTDEF int LIBCCALL libc_dos_truncate64(char const *file, pos64_t length);
INTDEF int LIBCCALL libc_ftruncateat(fd_t dfd, char const *file, pos32_t length, int flags);
INTDEF int LIBCCALL libc_ftruncateat64(fd_t dfd, char const *file, pos64_t length, int flags);
INTDEF int LIBCCALL libc_dos_ftruncateat(fd_t dfd, char const *file, pos32_t length, int flags);
INTDEF int LIBCCALL libc_dos_ftruncateat64(fd_t dfd, char const *file, pos64_t length, int flags);
INTDEF int LIBCCALL libc_chroot(char const *path);
INTDEF int LIBCCALL libc_dos_chroot(char const *path);
INTDEF char *LIBCCALL libd_getdcwd(int drive, char *buf, size_t size);
INTDEF char *LIBCCALL libd_dos_getdcwd(int drive, char *buf, size_t size);
INTDEF int LIBCCALL libd_chdrive(int drive);
INTDEF int LIBCCALL libd_getdrive(void);
INTDEF u32 LIBCCALL libd_getdrives(void);
/* STAT (KOS) */
struct __kos_stat;
struct __kos_stat64;
INTDEF int LIBCCALL libc_kfstat(fd_t fd, struct __kos_stat *buf);
INTDEF int LIBCCALL libc_kfstat64(fd_t fd, struct __kos_stat64 *buf);
INTDEF int LIBCCALL libc_kstat(char const *file, struct __kos_stat *buf);
INTDEF int LIBCCALL libc_kstat64(char const *file, struct __kos_stat64 *buf);
INTDEF int LIBCCALL libc_kfstatat(fd_t dfd, char const *file, struct __kos_stat *buf, int flags);
INTDEF int LIBCCALL libc_kfstatat64(fd_t dfd, char const *file, struct __kos_stat64 *buf, int flags);
INTDEF int LIBCCALL libc_klstat(char const *file, struct __kos_stat *buf);
INTDEF int LIBCCALL libc_klstat64(char const *file, struct __kos_stat64 *buf);
INTDEF int LIBCCALL libc_dos_kstat(char const *file, struct __kos_stat *buf);
INTDEF int LIBCCALL libc_dos_kstat64(char const *file, struct __kos_stat64 *buf);
INTDEF int LIBCCALL libc_dos_kfstatat(fd_t dfd, char const *file, struct __kos_stat *buf, int flags);
INTDEF int LIBCCALL libc_dos_kfstatat64(fd_t dfd, char const *file, struct __kos_stat64 *buf, int flags);
INTDEF int LIBCCALL libc_dos_klstat(char const *file, struct __kos_stat *buf);
INTDEF int LIBCCALL libc_dos_klstat64(char const *file, struct __kos_stat64 *buf);
/* STAT (GLC) */
struct __glc_stat;
struct __glc_stat64;
INTDEF int LIBCCALL libc_fstat(fd_t fd, struct __glc_stat *buf);
INTDEF int LIBCCALL libc_fstat64(fd_t fd, struct __glc_stat64 *buf);
INTDEF int LIBCCALL libc_stat(char const *file, struct __glc_stat *buf);
INTDEF int LIBCCALL libc_stat64(char const *file, struct __glc_stat64 *buf);
INTDEF int LIBCCALL libc_fstatat(fd_t dfd, char const *file, struct __glc_stat *buf, int flags);
INTDEF int LIBCCALL libc_fstatat64(fd_t dfd, char const *file, struct __glc_stat64 *buf, int flags);
INTDEF int LIBCCALL libc_lstat(char const *file, struct __glc_stat *buf);
INTDEF int LIBCCALL libc_lstat64(char const *file, struct __glc_stat64 *buf);
INTDEF int LIBCCALL libc_dos_stat(char const *file, struct __glc_stat *buf);
INTDEF int LIBCCALL libc_dos_stat64(char const *file, struct __glc_stat64 *buf);
INTDEF int LIBCCALL libc_dos_fstatat(fd_t dfd, char const *file, struct __glc_stat *buf, int flags);
INTDEF int LIBCCALL libc_dos_fstatat64(fd_t dfd, char const *file, struct __glc_stat64 *buf, int flags);
INTDEF int LIBCCALL libc_dos_lstat(char const *file, struct __glc_stat *buf);
INTDEF int LIBCCALL libc_dos_lstat64(char const *file, struct __glc_stat64 *buf);
INTDEF int LIBCCALL libc_version_fxstat(int ver, fd_t fd, struct __glc_stat *statbuf);
INTDEF int LIBCCALL libc_version_fxstat64(int ver, fd_t fd, struct __glc_stat64 *statbuf);
INTDEF int LIBCCALL libc_version_xstat(int ver, char const *filename, struct __glc_stat *statbuf);
INTDEF int LIBCCALL libc_version_xstat64(int ver, char const *filename, struct __glc_stat64 *statbuf);
INTDEF int LIBCCALL libc_version_lxstat(int ver, char const *filename, struct __glc_stat *statbuf);
INTDEF int LIBCCALL libc_version_lxstat64(int ver, char const *filename, struct __glc_stat64 *statbuf);
INTDEF int LIBCCALL libc_version_fxstatat(int ver, fd_t fd, char const *filename, struct __glc_stat *statbuf, int flags);
INTDEF int LIBCCALL libc_version_fxstatat64(int ver, fd_t fd, char const *filename, struct __glc_stat64 *statbuf, int flags);
INTDEF int LIBCCALL libc_dos_version_xstat(int ver, char const *filename, struct __glc_stat *statbuf);
INTDEF int LIBCCALL libc_dos_version_xstat64(int ver, char const *filename, struct __glc_stat64 *statbuf);
INTDEF int LIBCCALL libc_dos_version_lxstat(int ver, char const *filename, struct __glc_stat *statbuf);
INTDEF int LIBCCALL libc_dos_version_lxstat64(int ver, char const *filename, struct __glc_stat64 *statbuf);
INTDEF int LIBCCALL libc_dos_version_fxstatat(int ver, fd_t fd, char const *filename, struct __glc_stat *statbuf, int flags);
INTDEF int LIBCCALL libc_dos_version_fxstatat64(int ver, fd_t fd, char const *filename, struct __glc_stat64 *statbuf, int flags);
/* STAT (DOS) */
struct __dos_stat32;
struct __dos_stat32i64;
struct __dos_stat64;
struct utimbuf32;
struct utimbuf64;
INTDEF int LIBCCALL libd_fstat32(fd_t fd, struct __dos_stat32 *buf);
INTDEF int LIBCCALL libd_fstat32i64(fd_t fd, struct __dos_stat32i64 *buf);
INTDEF int LIBCCALL libd_fstat64(fd_t fd, struct __dos_stat64 *buf);
INTDEF int LIBCCALL libd_stat32(char const *file, struct __dos_stat32 *buf);
INTDEF int LIBCCALL libd_stat32i64(char const *file, struct __dos_stat32i64 *buf);
INTDEF int LIBCCALL libd_stat64(char const *file, struct __dos_stat64 *buf);
INTDEF int LIBCCALL libd_dos_stat32(char const *file, struct __dos_stat32 *buf);
INTDEF int LIBCCALL libd_dos_stat32i64(char const *file, struct __dos_stat32i64 *buf);
INTDEF int LIBCCALL libd_dos_stat64(char const *file, struct __dos_stat64 *buf);
/* FILESYSTEM TIME MODIFICATION. */
INTDEF int LIBCCALL libc_futime(fd_t fd, struct utimbuf32 const *file_times);
INTDEF int LIBCCALL libc_futime64(fd_t fd, struct utimbuf64 const *file_times);
INTDEF int LIBCCALL libc_futimens(fd_t fd, struct timespec32 const times[2]);
INTDEF int LIBCCALL libc_futimens64(fd_t fd, struct timespec64 const times[2]);
INTDEF int LIBCCALL libc_futimes(fd_t fd, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_futimes64(fd_t fd, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_utimensat(fd_t dfd, char const *path, struct timespec32 const times[2], int flags);
INTDEF int LIBCCALL libc_dos_utimensat(fd_t dfd, char const *path, struct timespec32 const times[2], int flags);
INTDEF int LIBCCALL libc_utimensat64(fd_t dfd, char const *path, struct timespec64 const times[2], int flags);
INTDEF int LIBCCALL libc_dos_utimensat64(fd_t dfd, char const *path, struct timespec64 const times[2], int flags);
INTDEF int LIBCCALL libc_futimeat(fd_t dfd, char const *file, struct utimbuf32 const *file_times, int flags);
INTDEF int LIBCCALL libc_dos_futimeat(fd_t dfd, char const *file, struct utimbuf32 const *file_times, int flags);
INTDEF int LIBCCALL libc_futimeat64(fd_t dfd, char const *file, struct utimbuf64 const *file_times, int flags);
INTDEF int LIBCCALL libc_dos_futimeat64(fd_t dfd, char const *file, struct utimbuf64 const *file_times, int flags);
INTDEF int LIBCCALL libc_utime(char const *file, struct utimbuf32 const *file_times);
INTDEF int LIBCCALL libc_dos_utime(char const *file, struct utimbuf32 const *file_times);
INTDEF int LIBCCALL libc_utime64(char const *file, struct utimbuf64 const *file_times);
INTDEF int LIBCCALL libc_dos_utime64(char const *file, struct utimbuf64 const *file_times);
INTDEF int LIBCCALL libc_impl_futimesat(fd_t dfd, char const *file, struct timeval32 const tvp[2], int flags);
INTDEF int LIBCCALL libc_impl_futimesat64(fd_t dfd, char const *file, struct timeval64 const tvp[2], int flags);
INTDEF int LIBCCALL libc_utimes(char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_utimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_dos_utimes(char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_dos_utimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_lutimes(char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_lutimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_dos_lutimes(char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_dos_lutimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_futimesat(fd_t dfd, char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_futimesat64(fd_t dfd, char const *file, struct timeval64 const tvp[2]);
INTDEF int LIBCCALL libc_dos_futimesat(fd_t dfd, char const *file, struct timeval32 const tvp[2]);
INTDEF int LIBCCALL libc_dos_futimesat64(fd_t dfd, char const *file, struct timeval64 const tvp[2]);
/* READ/WRITE */
INTDEF ssize_t LIBCCALL libc_read(fd_t fd, void *buf, size_t bufsize);
INTDEF ssize_t LIBCCALL libc_write(fd_t fd, void const *buf, size_t bufsize);
INTDEF int LIBCCALL libd_read(fd_t fd, void *buf, unsigned int bufsize);
INTDEF int LIBCCALL libd_write(fd_t fd, void const *buf, unsigned int bufsize);
INTDEF off32_t LIBCCALL libc_lseek(fd_t fd, off32_t offset, int whence);
INTDEF off64_t LIBCCALL libc_lseek64(fd_t fd, off64_t offset, int whence);
INTDEF ssize_t LIBCCALL libc_pread(fd_t fd, void *buf, size_t bufsize, pos32_t offset);
INTDEF ssize_t LIBCCALL libc_pread64(fd_t fd, void *buf, size_t bufsize, pos64_t offset);
INTDEF ssize_t LIBCCALL libc_pwrite(fd_t fd, void const *buf, size_t bufsize, pos32_t offset);
INTDEF ssize_t LIBCCALL libc_pwrite64(fd_t fd, void const *buf, size_t bufsize, pos64_t offset);
INTDEF ssize_t LIBCCALL libc_xreadf(fd_t fd, void *buf, size_t bufsize, oflag_t flags);
INTDEF ssize_t LIBCCALL libc_xwritef(fd_t fd, void const *buf, size_t bufsize, oflag_t flags);
INTDEF ssize_t LIBCCALL libc_xpreadf(fd_t fd, void *buf, size_t bufsize, pos32_t offset, oflag_t flags);
INTDEF ssize_t LIBCCALL libc_xpwritef(fd_t fd, void const *buf, size_t bufsize, pos32_t offset, oflag_t flags);
INTDEF ssize_t LIBCCALL libc_xpreadf64(fd_t fd, void *buf, size_t bufsize, pos64_t offset, oflag_t flags);
INTDEF ssize_t LIBCCALL libc_xpwritef64(fd_t fd, void const *buf, size_t bufsize, pos64_t offset, oflag_t flags);
struct pollfd;
INTDEF ssize_t LIBCCALL libc_poll(struct pollfd *fds, nfds_t nfds, int timeout);
INTDEF ssize_t LIBCCALL libc_ppoll(struct pollfd *fds, nfds_t nfds, struct timespec32 const *timeout, sigset_t const *ss);
INTDEF ssize_t LIBCCALL libc_ppoll64(struct pollfd *fds, nfds_t nfds, struct timespec64 const *timeout, sigset_t const *ss);
INTDEF ssize_t LIBCCALL libc_select(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval32 *timeout);
INTDEF ssize_t LIBCCALL libc_select64(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval64 *timeout);
INTDEF ssize_t LIBCCALL libc_pselect(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timespec32 const *timeout, sigset_t const *sigmask);
INTDEF ssize_t LIBCCALL libc_pselect64(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timespec64 const *timeout, sigset_t const *sigmask);
INTDEF int LIBCCALL libc_pause(void);
INTDEF int LIBCCALL libc_syncfs(fd_t fd);
INTDEF int LIBCCALL libc_group_member(gid_t gid);
INTDEF int LIBCCALL libc_getresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
INTDEF int LIBCCALL libc_getresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
INTDEF int LIBCCALL libc_setresuid(uid_t ruid, uid_t euid, uid_t suid);
INTDEF int LIBCCALL libc_setresgid(gid_t rgid, gid_t egid, gid_t sgid);
INTDEF size_t LIBCCALL libc_confstr(int name, char *buf, size_t buflen);
INTDEF void LIBCCALL libc_sync(void);
INTDEF int LIBCCALL libc_setreuid(uid_t ruid, uid_t euid);
INTDEF int LIBCCALL libc_setregid(gid_t rgid, gid_t egid);
INTDEF long int LIBCCALL libc_gethostid(void);
INTDEF int LIBCCALL libc_getpagesize(void) ;
INTDEF int LIBCCALL libc_getdtablesize(void);
INTDEF int LIBCCALL libc_seteuid(uid_t uid);
INTDEF int LIBCCALL libc_setegid(gid_t gid);
INTDEF int LIBCCALL libc_sethostid(long int id);
INTDEF int LIBCCALL libc_frevokeat(fd_t dfd, char const *file, int flags);
INTDEF int LIBCCALL libc_facctat(fd_t dfd, char const *name, int flags);
INTDEF int LIBCCALL libc_revoke(char const *file);
INTDEF int LIBCCALL libc_dos_revoke(char const *file);
INTDEF int LIBCCALL libc_profil(unsigned short int *sample_buffer, size_t size, size_t offset, unsigned int scale);
INTDEF int LIBCCALL libc_acct(char const *name);
INTDEF int LIBCCALL libc_dos_acct(char const *name);
INTDEF char *LIBCCALL libc_getusershell(void);
INTDEF void LIBCCALL libc_endusershell(void);
INTDEF void LIBCCALL libc_setusershell(void);
INTDEF int LIBCCALL libc_daemon(int nochdir, int noclose);
INTDEF long int ATTR_CDECL libc_syscall(long int sysno, ...);
INTDEF long long int ATTR_CDECL libc_lsyscall(long int sysno, ...) ASMNAME("libc_syscall");
INTDEF char *LIBCCALL libc_crypt(char const *key, char const *salt);
INTDEF void LIBCCALL libc_encrypt(char *glibc_block, int edflag);
INTDEF char *LIBCCALL libc_ctermid(char *s);
INTDEF long int LIBCCALL libc_sysconf(int name);
INTDEF int ATTR_CDECL libc_execl(char const *path, char const *args, ...);
INTDEF int ATTR_CDECL libc_execle(char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF int ATTR_CDECL libc_execlp(char const *file, char const *args, ...);
INTDEF int ATTR_CDECL libc_execlpe(char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF int ATTR_CDECL libc_dos_execl(char const *path, char const *args, ...);
INTDEF int ATTR_CDECL libc_dos_execle(char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF int ATTR_CDECL libc_dos_execlp(char const *file, char const *args, ...);
INTDEF int ATTR_CDECL libc_dos_execlpe(char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF int LIBCCALL libc_execv(char const *path, char *const argv[]);
INTDEF int LIBCCALL libc_execve(char const *path, char *const argv[], char *const envp[]);
INTDEF int LIBCCALL libc_execvp(char const *file, char *const argv[]);
INTDEF int LIBCCALL libc_execvpe(char const *file, char *const argv[], char *const envp[]);
INTDEF int LIBCCALL libc_dos_execv(char const *path, char *const argv[]);
INTDEF int LIBCCALL libc_dos_execve(char const *path, char *const argv[], char *const envp[]);
INTDEF int LIBCCALL libc_dos_execvp(char const *file, char *const argv[]);
INTDEF int LIBCCALL libc_dos_execvpe(char const *file, char *const argv[], char *const envp[]);
INTDEF int ATTR_CDECL libc_fexecl(int exec_fd, char const *args, ...);
INTDEF int ATTR_CDECL libc_fexecle(int exec_fd, char const *args, ... /*, char *const envp[] */);
INTDEF int LIBCCALL libc_fexecv(int exec_fd, char *const argv[]);
INTDEF int LIBCCALL libc_fexecve(int exec_fd, char *const argv[], char *const envp[]);
INTDEF int ATTR_CDECL libc_fexeclat(fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF int ATTR_CDECL libc_fexecleat(fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF int ATTR_CDECL libc_fexeclpat(char const *file, char const *args, ... /*, int flags*/);
INTDEF int ATTR_CDECL libc_fexeclpeat(char const *file, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF int ATTR_CDECL libc_dos_fexeclat(fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF int ATTR_CDECL libc_dos_fexecleat(fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF int ATTR_CDECL libc_dos_fexeclpat(char const *file, char const *args, ... /*, int flags*/);
INTDEF int ATTR_CDECL libc_dos_fexeclpeat(char const *file, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF int LIBCCALL libc_fexecvat(fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF int LIBCCALL libc_fexecveat(fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF int LIBCCALL libc_fexecvpat(char const *file, char *const argv[], int flags);
INTDEF int LIBCCALL libc_fexecvpeat(char const *file, char *const argv[], char *const envp[], int flags);
INTDEF int LIBCCALL libc_dos_fexecvat(fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF int LIBCCALL libc_dos_fexecveat(fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF int LIBCCALL libc_dos_fexecvpat(char const *file, char *const argv[], int flags);
INTDEF int LIBCCALL libc_dos_fexecvpeat(char const *file, char *const argv[], char *const envp[], int flags);
struct sysinfo;
INTDEF int LIBCCALL libc_sysinfo(struct sysinfo *info);
INTDEF int LIBCCALL libc_get_nprocs_conf(void);
INTDEF int LIBCCALL libc_get_nprocs(void);
INTDEF intptr_t LIBCCALL libc_get_phys_pages(void);
INTDEF intptr_t LIBCCALL libc_get_avphys_pages(void);

/* DOS's SPAWN functions */
INTDEF pid_t LIBCCALL libc_cwait(int *tstat, pid_t pid, int action);
INTDEF pid_t ATTR_CDECL libc_spawnl(int mode, char const *path, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_spawnle(int mode, char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_spawnlp(int mode, char const *file, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_spawnlpe(int mode, char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_dos_spawnl(int mode, char const *path, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_dos_spawnle(int mode, char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_dos_spawnlp(int mode, char const *file, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_dos_spawnlpe(int mode, char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t LIBCCALL libc_spawnv(int mode, char const *path, char *const argv[]);
INTDEF pid_t LIBCCALL libc_spawnve(int mode, char const *path, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_spawnvp(int mode, char const *file, char *const argv[]);
INTDEF pid_t LIBCCALL libc_spawnvpe(int mode, char const *file, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_dos_spawnv(int mode, char const *path, char *const argv[]);
INTDEF pid_t LIBCCALL libc_dos_spawnve(int mode, char const *path, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_dos_spawnvp(int mode, char const *file, char *const argv[]);
INTDEF pid_t LIBCCALL libc_dos_spawnvpe(int mode, char const *file, char *const argv[], char *const envp[]);
INTDEF pid_t ATTR_CDECL libc_fspawnl(int mode, int exec_fd, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_fspawnle(int mode, int exec_fd, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t LIBCCALL libc_fspawnv(int mode, int exec_fd, char *const argv[]);
INTDEF pid_t LIBCCALL libc_fspawnve(int mode, int exec_fd, char *const argv[], char *const envp[]);
INTDEF pid_t ATTR_CDECL libc_fspawnlat(int mode, fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_fspawnleat(int mode, fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF pid_t ATTR_CDECL libc_fspawnlpat(int mode, char const *file, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_fspawnlpeat(int mode, char const *file, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF pid_t ATTR_CDECL libc_dos_fspawnlat(int mode, fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_dos_fspawnleat(int mode, fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF pid_t ATTR_CDECL libc_dos_fspawnlpat(int mode, char const *file, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_dos_fspawnlpeat(int mode, char const *file, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF pid_t LIBCCALL libc_fspawnvat(int mode, fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_fspawnveat(int mode, fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF pid_t LIBCCALL libc_fspawnvpat(int mode, char const *file, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_fspawnvpeat(int mode, char const *file, char *const argv[], char *const envp[], int flags);
INTDEF pid_t LIBCCALL libc_dos_fspawnvat(int mode, fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_dos_fspawnveat(int mode, fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF pid_t LIBCCALL libc_dos_fspawnvpat(int mode, char const *file, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_dos_fspawnvpeat(int mode, char const *file, char *const argv[], char *const envp[], int flags);
/* UNISTD W/ exception support */
INTDEF int ATTR_CDECL libc_Xopen(char const *filename, oflag_t flags, ...);
INTDEF int ATTR_CDECL libc_Xopenat(fd_t dfd, char const *filename, oflag_t flags, ...);
INTDEF int LIBCCALL libc_Xcreat(char const *file, mode_t mode);
INTDEF ssize_t ATTR_CDECL libc_Xfcntl(fd_t fd, unsigned int cmd, ...);
INTDEF ssize_t ATTR_CDECL libc_Xioctl(fd_t fd, unsigned long cmd, ...);
INTDEF void LIBCCALL libc_Xpipe(int pipedes[2]);
INTDEF void LIBCCALL libc_Xpipe2(int pipedes[2], oflag_t flags);
INTDEF void LIBCCALL libc_Xfsync(fd_t fd);
INTDEF void LIBCCALL libc_Xfdatasync(fd_t fd);
INTDEF int LIBCCALL libc_Xdup(fd_t fd);
INTDEF int LIBCCALL libc_Xdup2(int ofd, int nfd);
INTDEF int LIBCCALL libc_Xdup3(int ofd, int nfd, int flags);
INTDEF void LIBCCALL libc_Xchdir(char const *path);
INTDEF void LIBCCALL libc_Xfchdirat(fd_t dfd, char const *path, int flags);
INTDEF void LIBCCALL libc_Xfchdir(fd_t fd);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xgetcwd(char *buf, size_t size);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xget_current_dir_name(void);
INTDEF long int LIBCCALL libc_Xpathconf(char const *path, int name);
INTDEF long int LIBCCALL libc_Xfpathconfat(fd_t dfd, char const *file, int name, int flags);
INTDEF long int LIBCCALL libc_Xfpathconf(fd_t fd, int name);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xrealpath(char const *name, char *resolved);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xfrealpath(fd_t fd, char *resolved, size_t bufsize);
INTDEF ATTR_MALLOC ATTR_RETNONNULL char *LIBCCALL libc_Xcanonicalize_file_name(char const *name);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xxfrealpath(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xxrealpath(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF ATTR_RETNONNULL char *LIBCCALL libc_Xxfrealpathat(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF size_t LIBCCALL libc_Xxfrealpath2(fd_t fd, char *buf, size_t bufsize, unsigned int type);
INTDEF size_t LIBCCALL libc_Xxrealpath2(char const *path, char *buf, size_t bufsize, unsigned int type);
INTDEF size_t LIBCCALL libc_Xxfrealpathat2(fd_t dfd, char const *path, int flags, char *buf, size_t bufsize, unsigned int type);
INTDEF void LIBCCALL libc_Xchown(char const *file, uid_t owner, gid_t group);
INTDEF void LIBCCALL libc_Xfchown(fd_t fd, uid_t owner, gid_t group);
INTDEF void LIBCCALL libc_Xlchown(char const *file, uid_t owner, gid_t group);
INTDEF void LIBCCALL libc_Xfchownat(fd_t dfd, char const *file, uid_t owner, gid_t group, int flags);
INTDEF void LIBCCALL libc_Xfchmod(fd_t fd, mode_t mode);
INTDEF void LIBCCALL libc_Xchmod(char const *file, mode_t mode);
INTDEF void LIBCCALL libc_Xlchmod(char const *file, mode_t mode);
INTDEF void LIBCCALL libc_Xfchmodat(fd_t dfd, char const *file, mode_t mode, int flags);
INTDEF void LIBCCALL libc_Xlink(char const *from, char const *to);
INTDEF void LIBCCALL libc_Xlinkat(int fromfd, char const *from, int tofd, char const *to, int flags);
INTDEF void LIBCCALL libc_Xunlink(char const *name);
INTDEF void LIBCCALL libc_Xunlinkat(fd_t dfd, char const *name, int flags);
INTDEF void LIBCCALL libc_Xrmdir(char const *name);
INTDEF void LIBCCALL libc_Xremove(char const *name);
INTDEF void LIBCCALL libc_Xremoveat(fd_t dfd, char const *name);
INTDEF void LIBCCALL libc_Xrename(char const *oldname, char const *newname);
INTDEF void LIBCCALL libc_Xrenameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname);
INTDEF void LIBCCALL libc_Xfrenameat(fd_t oldfd, char const *oldname, fd_t newfd, char const *newname, int flags);
INTDEF void LIBCCALL libc_Xmkdir(char const *name, mode_t mode);
INTDEF void LIBCCALL libc_Xmkdirat(fd_t dfd, char const *name, mode_t mode);
INTDEF void LIBCCALL libc_Xfmkdirat(fd_t dfd, char const *name, mode_t mode, int flags);
INTDEF void LIBCCALL libc_Xsymlink(char const *from, char const *to);
INTDEF void LIBCCALL libc_Xsymlinkat(char const *from, int tofd, char const *to);
INTDEF void LIBCCALL libc_Xfsymlinkat(char const *from, int tofd, char const *to, int flags);
INTDEF void LIBCCALL libc_Xmknod(char const *path, mode_t mode, dev_t dev);
INTDEF void LIBCCALL libc_Xmknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev);
INTDEF void LIBCCALL libc_Xfmknodat(fd_t dfd, char const *path, mode_t mode, dev_t dev, int flags);
INTDEF void LIBCCALL libc_Xmkfifo(char const *path, mode_t mode);
INTDEF void LIBCCALL libc_Xmkfifoat(fd_t dfd, char const *path, mode_t mode);
INTDEF size_t LIBCCALL libc_Xfreadlink(fd_t fd, char *buf, size_t buflen);
INTDEF size_t LIBCCALL libc_Xreadlink(char const *path, char *buf, size_t buflen);
INTDEF size_t LIBCCALL libc_Xreadlinkat(fd_t dfd, char const *path, char *buf, size_t buflen);
INTDEF size_t LIBCCALL libc_Xfreadlinkat(fd_t dfd, char const *path, char *buf, size_t buflen, int flags);
INTDEF void LIBCCALL libc_Xaccess(char const *name, int type);
INTDEF void LIBCCALL libc_Xeaccess(char const *name, int type);
INTDEF void LIBCCALL libc_Xfaccessat(fd_t dfd, char const *file, int type, int flags);
INTDEF void LIBCCALL libc_Xftruncate(fd_t fd, pos32_t length);
INTDEF void LIBCCALL libc_Xftruncate64(fd_t fd, pos64_t length);
INTDEF void LIBCCALL libc_Xtruncate(char const *file, pos32_t length);
INTDEF void LIBCCALL libc_Xtruncate64(char const *file, pos64_t length);
INTDEF void LIBCCALL libc_Xftruncateat(fd_t dfd, char const *file, pos32_t length, int flags);
INTDEF void LIBCCALL libc_Xftruncateat64(fd_t dfd, char const *file, pos64_t length, int flags);
INTDEF void LIBCCALL libc_Xchroot(char const *path);
INTDEF ATTR_RETNONNULL char *LIBCCALL libd_Xgetdcwd(int drive, char *buf, size_t size);
INTDEF void LIBCCALL libd_Xchdrive(int drive);
INTDEF int LIBCCALL libd_Xgetdrive(void);
INTDEF void LIBCCALL libc_Xkfstat(fd_t fd, struct __kos_stat *buf);
INTDEF void LIBCCALL libc_Xkfstat64(fd_t fd, struct __kos_stat64 *buf);
INTDEF void LIBCCALL libc_Xkstat(char const *file, struct __kos_stat *buf);
INTDEF void LIBCCALL libc_Xkstat64(char const *file, struct __kos_stat64 *buf);
INTDEF void LIBCCALL libc_Xkfstatat(fd_t dfd, char const *file, struct __kos_stat *buf, int flags);
INTDEF void LIBCCALL libc_Xkfstatat64(fd_t dfd, char const *file, struct __kos_stat64 *buf, int flags);
INTDEF void LIBCCALL libc_Xklstat(char const *file, struct __kos_stat *buf);
INTDEF void LIBCCALL libc_Xklstat64(char const *file, struct __kos_stat64 *buf);
INTDEF void LIBCCALL libc_Xfutime(fd_t fd, struct utimbuf32 const *file_times);
INTDEF void LIBCCALL libc_Xfutime64(fd_t fd, struct utimbuf64 const *file_times);
INTDEF void LIBCCALL libc_Xfutimens(fd_t fd, struct timespec32 const times[2]);
INTDEF void LIBCCALL libc_Xfutimens64(fd_t fd, struct timespec64 const times[2]);
INTDEF void LIBCCALL libc_Xfutimes(fd_t fd, struct timeval32 const tvp[2]);
INTDEF void LIBCCALL libc_Xfutimes64(fd_t fd, struct timeval64 const tvp[2]);
INTDEF void LIBCCALL libc_Xutimensat(fd_t dfd, char const *path, struct timespec32 const times[2], int flags);
INTDEF void LIBCCALL libc_Xutimensat64(fd_t dfd, char const *path, struct timespec64 const times[2], int flags);
INTDEF void LIBCCALL libc_Xfutimeat(fd_t dfd, char const *file, struct utimbuf32 const *file_times, int flags);
INTDEF void LIBCCALL libc_Xfutimeat64(fd_t dfd, char const *file, struct utimbuf64 const *file_times, int flags);
INTDEF void LIBCCALL libc_Xutime(char const *file, struct utimbuf32 const *file_times);
INTDEF void LIBCCALL libc_Xutime64(char const *file, struct utimbuf64 const *file_times);
INTDEF void LIBCCALL libc_impl_Xfutimesat(fd_t fd, char const *file, struct timeval32 const tvp[2], int flags);
INTDEF void LIBCCALL libc_impl_Xfutimesat64(fd_t fd, char const *file, struct timeval64 const tvp[2], int flags);
INTDEF void LIBCCALL libc_Xutimes(char const *file, struct timeval32 const tvp[2]);
INTDEF void LIBCCALL libc_Xutimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF void LIBCCALL libc_Xlutimes(char const *file, struct timeval32 const tvp[2]);
INTDEF void LIBCCALL libc_Xlutimes64(char const *file, struct timeval64 const tvp[2]);
INTDEF void LIBCCALL libc_Xfutimesat(fd_t fd, char const *file, struct timeval32 const tvp[2]);
INTDEF void LIBCCALL libc_Xfutimesat64(fd_t fd, char const *file, struct timeval64 const tvp[2]);
INTDEF size_t LIBCCALL libc_Xread(fd_t fd, void *buf, size_t bufsize);
INTDEF size_t LIBCCALL libc_Xwrite(fd_t fd, void const *buf, size_t bufsize);
INTDEF pos32_t LIBCCALL libc_Xlseek(fd_t fd, off32_t offset, int whence);
INTDEF pos64_t LIBCCALL libc_Xlseek64(fd_t fd, off64_t offset, int whence);
INTDEF size_t LIBCCALL libc_Xpread(fd_t fd, void *buf, size_t bufsize, pos32_t offset);
INTDEF size_t LIBCCALL libc_Xpread64(fd_t fd, void *buf, size_t bufsize, pos64_t offset);
INTDEF size_t LIBCCALL libc_Xpwrite(fd_t fd, void const *buf, size_t bufsize, pos32_t offset);
INTDEF size_t LIBCCALL libc_Xpwrite64(fd_t fd, void const *buf, size_t bufsize, pos64_t offset);
INTDEF size_t LIBCCALL libc_Xxreadf(fd_t fd, void *buf, size_t bufsize, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xxwritef(fd_t fd, void const *buf, size_t bufsize, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xxpreadf(fd_t fd, void *buf, size_t bufsize, pos32_t offset, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xxpwritef(fd_t fd, void const *buf, size_t bufsize, pos32_t offset, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xxpreadf64(fd_t fd, void *buf, size_t bufsize, pos64_t offset, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xxpwritef64(fd_t fd, void const *buf, size_t bufsize, pos64_t offset, oflag_t flags);
INTDEF size_t LIBCCALL libc_Xpoll(struct pollfd *fds, nfds_t nfds, int timeout);
INTDEF size_t LIBCCALL libc_Xppoll(struct pollfd *fds, nfds_t nfds, struct timespec32 const *timeout, sigset_t const *ss);
INTDEF size_t LIBCCALL libc_Xppoll64(struct pollfd *fds, nfds_t nfds, struct timespec64 const *timeout, sigset_t const *ss);
INTDEF size_t LIBCCALL libc_Xselect(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval32 *timeout);
INTDEF size_t LIBCCALL libc_Xselect64(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timeval64 *timeout);
INTDEF size_t LIBCCALL libc_Xpselect(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timespec32 const *timeout, sigset_t const *sigmask);
INTDEF size_t LIBCCALL libc_Xpselect64(int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, struct timespec64 const *timeout, sigset_t const *sigmask);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xpause(void);
INTDEF void LIBCCALL libc_Xsyncfs(fd_t fd);
INTDEF void LIBCCALL libc_Xgroup_member(gid_t gid);
INTDEF void LIBCCALL libc_Xgetresuid(uid_t *ruid, uid_t *euid, uid_t *suid);
INTDEF void LIBCCALL libc_Xgetresgid(gid_t *rgid, gid_t *egid, gid_t *sgid);
INTDEF void LIBCCALL libc_Xsetresuid(uid_t ruid, uid_t euid, uid_t suid);
INTDEF void LIBCCALL libc_Xsetresgid(gid_t rgid, gid_t egid, gid_t sgid);
INTDEF size_t LIBCCALL libc_Xconfstr(int name, char *buf, size_t buflen);
INTDEF void LIBCCALL libc_Xsetreuid(uid_t ruid, uid_t euid);
INTDEF void LIBCCALL libc_Xsetregid(gid_t rgid, gid_t egid);
INTDEF long int LIBCCALL libc_Xgethostid(void);
INTDEF void LIBCCALL libc_Xsethostid(long int id);
INTDEF void LIBCCALL libc_Xseteuid(uid_t uid);
INTDEF void LIBCCALL libc_Xsetegid(gid_t gid);
INTDEF void LIBCCALL libc_Xgetdomainname(char *name, size_t buflen);
INTDEF void LIBCCALL libc_Xsetdomainname(char const *name, size_t len);
INTDEF void LIBCCALL libc_Xrevoke(char const *file);
INTDEF void LIBCCALL libc_Xprofil(unsigned short int *sample_buffer, size_t size, size_t offset, unsigned int scale);
INTDEF void LIBCCALL libc_Xacct(char const *name);
INTDEF void LIBCCALL libc_Xdaemon(int nochdir, int noclose);
INTDEF long int LIBCCALL libc_Xsysconf(int name);
INTDEF long int ATTR_CDECL libc_Xsyscall(long int sysno, ...);
INTDEF long long int ATTR_CDECL libc_Xlsyscall(long int sysno, ...) ASMNAME("libc_Xsyscall");
INTDEF void LIBCCALL libc_Xsysinfo(struct sysinfo *info);
INTDEF unsigned int LIBCCALL libc_Xget_nprocs_conf(void);
INTDEF unsigned int LIBCCALL libc_Xget_nprocs(void);
INTDEF uintptr_t LIBCCALL libc_Xget_phys_pages(void);
INTDEF uintptr_t LIBCCALL libc_Xget_avphys_pages(void);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xexecl(char const *path, char const *args, ...);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xexecle(char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xexeclp(char const *file, char const *args, ...);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xexeclpe(char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xexecv(char const *path, char *const argv[]);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xexecve(char const *path, char *const argv[], char *const envp[]);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xexecvp(char const *file, char *const argv[]);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xexecvpe(char const *file, char *const argv[], char *const envp[]);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexecl(int exec_fd, char const *args, ...);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexecle(int exec_fd, char const *args, ... /*, char *const envp[] */);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecv(int exec_fd, char *const argv[]);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecve(int exec_fd, char *const argv[], char *const envp[]);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexeclat(fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexecleat(fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexeclpat(char const *file, char const *args, ... /*, int flags*/);
INTDEF ATTR_NORETURN void ATTR_CDECL libc_Xfexeclpeat(char const *file, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecvat(fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecveat(fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecvpat(char const *file, char *const argv[], int flags);
INTDEF ATTR_NORETURN void LIBCCALL libc_Xfexecvpeat(char const *file, char *const argv[], char *const envp[], int flags);
INTDEF pid_t LIBCCALL libc_Xcwait(int *tstat, pid_t pid, int action);
INTDEF pid_t LIBCCALL libc_Xspawnv(int mode, char const *path, char *const argv[]);
INTDEF pid_t LIBCCALL libc_Xspawnve(int mode, char const *path, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_Xspawnvp(int mode, char const *file, char *const argv[]);
INTDEF pid_t LIBCCALL libc_Xspawnvpe(int mode, char const *file, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_Xfspawnv(int mode, int exec_fd, char *const argv[]);
INTDEF pid_t LIBCCALL libc_Xfspawnve(int mode, int exec_fd, char *const argv[], char *const envp[]);
INTDEF pid_t LIBCCALL libc_Xfspawnvat(int mode, fd_t dfd, char const *path, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_Xfspawnvpat(int mode, char const *file, char *const argv[], int flags);
INTDEF pid_t LIBCCALL libc_Xfspawnveat(int mode, fd_t dfd, char const *path, char *const argv[], char *const envp[], int flags);
INTDEF pid_t LIBCCALL libc_Xfspawnvpeat(int mode, char const *file, char *const argv[], char *const envp[], int flags);
INTDEF pid_t ATTR_CDECL libc_Xspawnl(int mode, char const *path, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_Xspawnle(int mode, char const *path, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_Xspawnlp(int mode, char const *file, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_Xspawnlpe(int mode, char const *file, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_Xfspawnl(int mode, int exec_fd, char const *args, ...);
INTDEF pid_t ATTR_CDECL libc_Xfspawnle(int mode, int exec_fd, char const *args, ... /*, char *const envp[] */);
INTDEF pid_t ATTR_CDECL libc_Xfspawnlat(int mode, fd_t dfd, char const *path, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_Xfspawnleat(int mode, fd_t dfd, char const *path, char const *args, ... /*, char *const envp[], int flags*/);
INTDEF pid_t ATTR_CDECL libc_Xfspawnlpat(int mode, char const *file, char const *args, ... /*, int flags*/);
INTDEF pid_t ATTR_CDECL libc_Xfspawnlpeat(int mode, char const *file, char const *args, ... /*, char *const envp[], int flags*/);
/* Misc. DOS functions. */
INTDEF WUNUSED int LIBCCALL libc_eof(fd_t fd);
INTDEF WUNUSED s32 LIBCCALL libc_filelength(fd_t fd);
INTDEF WUNUSED s64 LIBCCALL libc_filelengthi64(fd_t fd);
INTDEF WUNUSED s32 LIBCCALL libc_tell(fd_t fd);
INTDEF WUNUSED s64 LIBCCALL libc_telli64(fd_t fd);
INTDEF WUNUSED intptr_t LIBCCALL libc_get_osfhandle(fd_t fd);
INTDEF WUNUSED int LIBCCALL libc_open_osfhandle(intptr_t osfd, int flags);
INTDEF WUNUSED int ATTR_CDECL libc_sopen(char const *file, int oflag, int sflag, ...);
INTDEF WUNUSED int ATTR_CDECL libc_dos_sopen(char const *file, int oflag, int sflag, ...);
INTDEF WUNUSED errno_t ATTR_CDECL libc_sopen_s(int *fd, char const *file, int oflag, int sflag, ...);
INTDEF WUNUSED derrno_t ATTR_CDECL libc_dos_sopen_s(int *fd, char const *file, int oflag, int sflag, ...);


DECL_END
#endif /* __CC__ */

#endif /* !GUARD_LIBS_LIBC_UNISTD_H */
